// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAexjSHMnsHse0_Hx1mgVvX8o0fe_ey8v8',
    appId: '1:968493104763:web:d56f19f08e56647fe96cde',
    messagingSenderId: '968493104763',
    projectId: 'online-groceries-1d35d',
    authDomain: 'online-groceries-1d35d.firebaseapp.com',
    storageBucket: 'online-groceries-1d35d.appspot.com',
    measurementId: 'G-YJJZKK7WNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4pE_63j2-u5mfkNNfB5-fm5J3-UckHHY',
    appId: '1:968493104763:android:3c15ed56520defa2e96cde',
    messagingSenderId: '968493104763',
    projectId: 'online-groceries-1d35d',
    storageBucket: 'online-groceries-1d35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn4tFqckXcEWZ9VYXyidrwan-kLKXuchY',
    appId: '1:968493104763:ios:73a95feb5323bd1ee96cde',
    messagingSenderId: '968493104763',
    projectId: 'online-groceries-1d35d',
    storageBucket: 'online-groceries-1d35d.appspot.com',
    iosBundleId: 'com.example.onlineGroceries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn4tFqckXcEWZ9VYXyidrwan-kLKXuchY',
    appId: '1:968493104763:ios:c73dfa1b53103bebe96cde',
    messagingSenderId: '968493104763',
    projectId: 'online-groceries-1d35d',
    storageBucket: 'online-groceries-1d35d.appspot.com',
    iosBundleId: 'com.example.onlineGroceries.RunnerTests',
  );
}
